---
- hosts: localhost
  become: true
  tasks:
  - name: Install R & rstudio packages
    wget: https://download2.rstudio.org/rstudio-server-rhel-1.1.442-x86_64.rpm
    yum: name={{item}}
    with_items:
    - epel-release
    - rstudio-server-rhel-1.1.442-x86_64.rpm
    - R
    - rstudio
